name: "JKem: Test and Publish Doc"
on:
  push:
   branches:
   - main
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTFLAGS: "-D warnings -W unreachable-pub"
  RUSTUP_MAX_RETRIES: 10

jobs:
  rustdoc:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      run: rustup update --no-self-update stable

    - name: Cargo Check
      run: cargo check
      
    - name: Build Documentation
      run: cargo doc --all --no-deps

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v4
      with:
        deploy_key: ${{ secrets.GITHUB_TOKEN }}
        external_repository: wsm25/wsm25.github.io
        publish_branch: main
        publish_dir: target/doc
        destination_dir: jkem